Repository RedArrowRobotics/2025RobotCode, pull requests merged in 2025-02, with the labels that each got.

#11 Simplify Controls Part 2
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
Labels: enhancement

#14 Subsystem/coral scoring device (Coral Scoring Device)
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/CageSubsystem.java
  src/main/java/frc/robot/subsystems/CoralScoringDeviceSubsystem.java
Labels: enhancement, help wanted, good first issue, question

#29 Dimensioned Encoders
  src/main/java/frc/robot/encoder/AngleAbsoluteEncoder.java
  src/main/java/frc/robot/encoder/AngleEncoder.java
  src/main/java/frc/robot/encoder/AngleRelativeEncoder.java
  src/main/java/frc/robot/encoder/DistanceEncoder.java
  src/main/java/frc/robot/encoder/LinearEncoder.java
Labels: enhancement

#15 Subsystem/Elevator
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
Labels: enhancement

#22 Subsystem/CoralScoringDevice (2)
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/CoralScoringArm.java
  src/main/java/frc/robot/commands/PIDCommand.java
  src/main/java/frc/robot/subsystems/CoralScoringDeviceSubsystem.java
Labels: enhancement

#32 Speed-Change-Button
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
Labels: enhancement, good first issue

#33 Controls
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/CoralScoringDeviceSubsystem.java
  src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
  src/test/java/EncoderTests.java
Labels: enhancement
