Repository RedArrowRobotics/2025RobotCode, pull requests merged in 2025-03, with the labels that each got.

#47 Cage Input Fix
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, good first issue

#51 Update and Set
  build.gradle
  src/main/java/frc/robot/Constants.java
Labels: enhancement, good first issue

#48 Named Commands
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, good first issue, important

#57 Control Numbers and Invert Y Axis
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/RobotContainer.java
Labels: important

#55 Cage Grabber
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/CageSubsystem.java
Labels: enhancement, important

#62 Trigger Intake
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/AlignToAprilTag.java
Labels: important

#56 Paths!
  src/main/deploy/pathplanner/autos/Left Auto.auto
  src/main/deploy/pathplanner/autos/Middle Auto.auto
  src/main/deploy/pathplanner/autos/Right Auto.auto
  src/main/deploy/pathplanner/paths/Bottom Forward.path
  src/main/deploy/pathplanner/paths/Middle Forward.path
  src/main/deploy/pathplanner/paths/Top Forward.path
  src/main/deploy/pathplanner/settings.json
Labels: enhancement, important

#64 Adding Manual Control for Coral Scoring Device
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/RobotContainer.java
Labels: important

#63 Rotating the Drive for Red Alliance
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/DriveSubsystem.java
Labels: important

#66 Manual Drop Coral Button
  src/main/java/frc/robot/ControlInputs.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/CoralScoringDeviceSubsystem.java
  src/main/java/frc/robot/subsystems/ElevatorSubsystem.java
Labels: enhancement, good first issue

#68 Climbing Touch Sensor Limit
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/CageSubsystem.java
Labels: good first issue, important
